<section>
    <h1>Congratulations!</h1>
</section>



<section id="addNew" ng-controller="add_products">
    <input placeholder="Image" type="text" ng-model="new.img"/>
    <input placeholder="Title" type="text" ng-model="new.title"/>
    <input placeholder="Category" type="text" ng-model="new.category"/>
    <input placeholder="Price" type="text" ng-model="new.price"/>
    <button ng-click="add();">Add</button>
</section>